server:
  port: 5555

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/arrMan-dev/server-config.git
